/**
 * Tutorial Steps Definition
 * 
 * This file defines the sequence of tutorial steps.
 * Text content is referenced via i18n keys (tutorial namespace).
 * Actual text lives in Application/i18n/locales/{en,fr}/tutorial.json.
 * 
 * Generated by TutorialStepEditor DevTool.
 */

import { TutorialStep } from '../../types/tutorialTypes';

export const TUTORIAL_STEPS: TutorialStep[] = [
    // Step 1: Welcome — no overlays, no actions allowed
    {
        id: 'step_1',
        titleKey: 'tutorial:tutorial.steps.step_1.title',
        textKey: 'tutorial:tutorial.steps.step_1.text',
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 2: Mission context — same as step 1
    {
        id: 'step_2',
        titleKey: 'tutorial:tutorial.steps.step_2.title',
        textKey: 'tutorial:tutorial.steps.step_2.text',
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 3: Map overview — overlay on side panels, highlight all map locations
    {
        id: 'step_3',
        titleKey: 'tutorial:tutorial.steps.step_3.title',
        textKey: 'tutorial:tutorial.steps.step_3.text',
        blockedZones: ['LEFT_PANEL', 'RIGHT_PANEL'],
        highlights: [{ zone: 'MAP_LOCATIONS' }, { zone: 'MAP_ROADS' }],
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 4: City info — overlay removed on right panel, left still blocked
    {
        id: 'step_4',
        titleKey: 'tutorial:tutorial.steps.step_4.title',
        textKey: 'tutorial:tutorial.steps.step_4.text',
        blockedZones: ['LEFT_PANEL'],
        scrollOnlyZones: ['RIGHT_PANEL'],
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 5: Gold & Food — same as step 4
    {
        id: 'step_5',
        titleKey: 'tutorial:tutorial.steps.step_5.title',
        textKey: 'tutorial:tutorial.steps.step_5.text',
        blockedZones: ['LEFT_PANEL'],
        scrollOnlyZones: ['RIGHT_PANEL'],
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 6: Stability — same as step 4
    {
        id: 'step_6',
        titleKey: 'tutorial:tutorial.steps.step_6.title',
        textKey: 'tutorial:tutorial.steps.step_6.text',
        blockedZones: ['LEFT_PANEL'],
        scrollOnlyZones: ['RIGHT_PANEL'],
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 7: Stability levers — same as step 4
    {
        id: 'step_7',
        titleKey: 'tutorial:tutorial.steps.step_7.title',
        textKey: 'tutorial:tutorial.steps.step_7.text',
        blockedZones: ['LEFT_PANEL'],
        scrollOnlyZones: ['RIGHT_PANEL'],
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 8: Administration button — highlight it, auto-advance when TerritorialMenu opens
    {
        id: 'step_8',
        titleKey: 'tutorial:tutorial.steps.step_8.title',
        textKey: 'tutorial:tutorial.steps.step_8.text',
        blockedZones: ['LEFT_PANEL'],
        highlights: [{ zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="admin-button"]' }],
        allowedActions: [{ type: 'OPEN_MENU', target: 'TERRITORIAL_MENU' }],
        autoAdvanceOn: 'TERRITORIAL_MENU_OPEN',
        hideNextButton: true,
    },
    // Step 9: Tax management — can modify taxes, auto-advance when menu closes
    {
        id: 'step_9',
        titleKey: 'tutorial:tutorial.steps.step_9.title',
        textKey: 'tutorial:tutorial.steps.step_9.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="personal-tax-slider"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="trade-tax-slider"]' },
        ],
        allowedActions: [{ type: 'CHANGE_TAX' }, { type: 'CLOSE_MENU' }],
        autoAdvanceOn: 'TERRITORIAL_MENU_CLOSE',
        hideNextButton: true,
    },
    // Step 10: Left panel — overlay removed, can hover/select territories
    {
        id: 'step_10',
        titleKey: 'tutorial:tutorial.steps.step_10.title',
        textKey: 'tutorial:tutorial.steps.step_10.text',
        highlights: [{ zone: 'LEFT_PANEL' }],
        allowedActions: [{ type: 'CLICK_LOCATION' }, { type: 'OPEN_MENU', target: 'TERRITORIAL_MENU' }],
    },
    // Step 11: Territory overview — same as step 10
    {
        id: 'step_11',
        titleKey: 'tutorial:tutorial.steps.step_11.title',
        textKey: 'tutorial:tutorial.steps.step_11.text',
        allowedActions: [{ type: 'CLICK_LOCATION' }, { type: 'OPEN_MENU', target: 'TERRITORIAL_MENU' }],
    },
    // Step 12: Population lesson — same as step 10
    {
        id: 'step_12',
        titleKey: 'tutorial:tutorial.steps.step_12.title',
        textKey: 'tutorial:tutorial.steps.step_12.text',
        allowedActions: [{ type: 'CLICK_LOCATION' }, { type: 'OPEN_MENU', target: 'TERRITORIAL_MENU' }],
    },
    // Step 13: Leaders introduction — can open LeadersModal/Panel, browse; no recruit/governor/clandestine/moves
    // On exit → close LeadersModal if open (handled by useTutorialStepEffects)
    {
        id: 'step_13',
        titleKey: 'tutorial:tutorial.steps.step_13.title',
        textKey: 'tutorial:tutorial.steps.step_13.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="leaders-button"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="leaders-panel"]' },
        ],
        allowedActions: [{ type: 'OPEN_LEADERS' }],
    },
    // Step 14: Appoint Enoch governor of Tamnit (Phase 2 — complex: filtered dropdown, auto-advance on governor appointment)
    {
        id: 'step_14',
        titleKey: 'tutorial:tutorial.steps.step_14.title',
        textKey: 'tutorial:tutorial.steps.step_14.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="leaders-button"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="leaders-panel"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="location-tamnit_tutorial"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="nominate-governor"]' },
        ],
        allowedActions: [
            { type: 'OPEN_LEADERS' },
            { type: 'CLICK_LOCATION' },
            { type: 'APPOINT_GOVERNOR', target: 'enoch_tutorial:tamnit_tutorial' },
        ],
        autoAdvanceOn: 'GOVERNOR_APPOINTED:tamnit_tutorial',
        hideNextButton: true,
    },
    // Step 15: Open governor menu — highlight Manage Governor + Enoch card, auto-advance on open
    {
        id: 'step_15',
        titleKey: 'tutorial:tutorial.steps.step_15.title',
        textKey: 'tutorial:tutorial.steps.step_15.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="manage-governor-button"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="leader-card-enoch_tutorial"]' },
        ],
        allowedActions: [
            { type: 'CLICK_LOCATION' },
            { type: 'OPEN_GOVERNOR_MENU' },
        ],
        autoAdvanceOn: 'GOVERNOR_MENU_OPENED',
        hideNextButton: true,
    },
    // Step 16: Use governor menu — can choose actions, not TerritorialMenu or NominateGovernor
    // On exit → close GovernorMenu if open (handled by useTutorialStepEffects)
    {
        id: 'step_16',
        titleKey: 'tutorial:tutorial.steps.step_16.title',
        textKey: 'tutorial:tutorial.steps.step_16.text',
        allowedActions: [
            { type: 'USE_GOVERNOR_ACTIONS' },
            { type: 'CLOSE_MENU' },
        ],
        autoAdvanceOn: 'GOVERNOR_MENU_CLOSED',
    },
    // Step 17: Click army on bridge — highlight bridge road stage + delta_province + army
    // Auto-advance when bridge selected; if manual advance → auto-select bridge (useTutorialStepEffects)
    {
        id: 'step_17',
        titleKey: 'tutorial:tutorial.steps.step_17.title',
        textKey: 'tutorial:tutorial.steps.step_17.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="road-stage-canopy_captainship_tutorial_delta_province_tutorial_road-1"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="location-delta_province_tutorial"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial~="army-barrett_road_army"]' },
        ],
        allowedActions: [
            { type: 'CLICK_ROAD_STAGE', target: 'canopy_captainship_tutorial_delta_province_tutorial_road:1' },
        ],
        autoAdvanceOn: 'ROAD_STAGE_SELECTED:canopy_captainship_tutorial_delta_province_tutorial_road:1',
        hideNextButton: true,
    },
    // Step 18: End turn — army advances, scripted AI moves (Phase 3 — scripted AI)
    {
        id: 'step_18',
        titleKey: 'tutorial:tutorial.steps.step_18.title',
        textKey: 'tutorial:tutorial.steps.step_18.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="end-turn-button"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="stationed-forces"]' },
        ],
        allowedActions: [{ type: 'END_TURN' }],
        autoAdvanceOn: 'TURN_ENDED',
        hideNextButton: true,
    },
    // Step 19: Manage territories + capture Shama (Phase 3 — scripted AI + fine restrictions)
    {
        id: 'step_19',
        titleKey: 'tutorial:tutorial.steps.step_19.title',
        textKey: 'tutorial:tutorial.steps.step_19.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="location-delta_province_tutorial"]' },
        ],
        allowedActions: [
            { type: 'CLICK_LOCATION' },
            { type: 'OPEN_LEADERS' },
            { type: 'OPEN_MENU', target: 'TERRITORIAL_MENU' },
            { type: 'OPEN_GOVERNOR_MENU' },
            { type: 'USE_GOVERNOR_ACTIONS' },
            { type: 'APPOINT_GOVERNOR' },
            { type: 'CLOSE_MENU' },
            { type: 'RECRUIT' },
            { type: 'CHANGE_TAX' },
            { type: 'MOVE_ARMY', target: 'shama_tutorial' },
        ],
        autoAdvanceOn: 'SHAMA_CAPTURED',
        hideNextButton: true,
    },
    // Step 20: Access clandestine actions of Sufet Askarbal (Phase 2)
    {
        id: 'step_20',
        titleKey: 'tutorial:tutorial.steps.step_20.title',
        textKey: 'tutorial:tutorial.steps.step_20.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="leader-card-sufet_askarbal"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="location-high_cliffs_tutorial"]' },
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="clandestine-operations-button"]' },
        ],
        allowedActions: [
            { type: 'CLICK_LOCATION' },
            { type: 'OPEN_LEADERS' },
            { type: 'OPEN_MENU', target: 'TERRITORIAL_MENU' },
            { type: 'OPEN_GOVERNOR_MENU' },
            { type: 'USE_GOVERNOR_ACTIONS' },
            { type: 'APPOINT_GOVERNOR' },
            { type: 'CLOSE_MENU' },
            { type: 'RECRUIT' },
            { type: 'CHANGE_TAX' },
            { type: 'MOVE_ARMY' },
            { type: 'OPEN_CLANDESTINE_MENU', target: 'high_cliffs_tutorial' },
        ],
        autoAdvanceOn: 'CLANDESTINE_MENU_OPENED:high_cliffs_tutorial',
        hideNextButton: true,
    },
    // Step 21: Clandestine info (read-only) — NO actions, not even close menu
    {
        id: 'step_21',
        titleKey: 'tutorial:tutorial.steps.step_21.title',
        textKey: 'tutorial:tutorial.steps.step_21.text',
        allowedActions: [{ type: 'NONE' }],
    },
    // Step 22: Prepare grand insurrection (Phase 2 — slider validation + GRAND_INSURRECTION)
    {
        id: 'step_22',
        titleKey: 'tutorial:tutorial.steps.step_22.title',
        textKey: 'tutorial:tutorial.steps.step_22.text',
        highlights: [
            { zone: 'SPECIFIC_ELEMENT', cssSelector: '[data-tutorial="clandestine-action-prepare-grand-insurrection"]' },
        ],
        allowedActions: [
            { type: 'PREPARE_GRAND_INSURRECTION', target: 'high_cliffs_tutorial:500' },
        ],
        autoAdvanceOn: 'GRAND_INSURRECTION_LAUNCHED',
        hideNextButton: true,
    },
    // Step 23: Tutorial complete — free play
    {
        id: 'step_23',
        titleKey: 'tutorial:tutorial.steps.step_23.title',
        textKey: 'tutorial:tutorial.steps.step_23.text',
        allowedActions: [{ type: 'ANY' }],
    },
];
